routes/web.php
<?php

use App\Http\Controllers\AuthorController;
use App\Http\Controllers\BookController;
use App\Http\Controllers\GenreController;
use App\Http\Controllers\MainController;
use App\Http\Controllers\ProfileController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [MainController::class, 'index'])->middleware(['auth', 'verified'])->name('main.index');

Route::controller(BookController::class)->group(function () {
    Route::middleware(['auth', 'verified'])->group(function () {
        Route::get('/books', 'index')->name('books.index');
        Route::get('/books/{book}', 'show')->name('books.show');
        Route::get('/books/{book}/update', 'update')->name('books.update');
        Route::get('/books/{book}/delete', 'delete')->name('books.delete');
        Route::delete('/books/{book}/destroy', 'destroy')->name('books.destroy');
        Route::get('/book/create', 'create')->name('book.create');
        Route::post('/books/store', 'store')->name('books.store');
        Route::put('/books/{book}/save', 'save')->name('books.save');
        Route::get('/book/search', 'search')->name('books.search');
    });
});

Route::controller(AuthorController::class)->group(function () {
    Route::middleware(['auth', 'verified'])->group(function () {
        Route::get('/authors', 'index')->name('authors.index');
        Route::get('/authors/{author}', 'show')->name('authors.show');
        Route::get('/authors/{author}/update', 'update')->name('authors.update');
        Route::get('/authors/{author}/delete', 'delete')->name('authors.delete');
        Route::delete('/authors/{author}/destroy', 'destroy')->name('authors.destroy');
        Route::get('/author/create', 'create')->name('author.create');
        Route::post('/authors/store', 'store')->name('authors.store');
        Route::put('/authors/{author}/save', 'save')->name('authors.save');
    });
});

Route::controller(GenreController::class)->group(function () {
    Route::middleware(['auth', 'verified'])->group(function () {
        Route::get('/genres', 'index')->name('genres.index');
        Route::get('/genres/{genre}', 'show')->name('genres.show');
        Route::get('/genres/{genre}/update', 'update')->name('genres.update');
        Route::get('/genres/{genre}/delete', 'delete')->name('genres.delete');
        Route::delete('/genres/{genre}/destroy', 'destroy')->name('genres.destroy');
        Route::get('/genre/create', 'create')->name('genre.create');
        Route::post('/genres/store', 'store')->name('genres.store');
        Route::put('/genres/{genre}/save', 'save')->name('genres.save');
    });
});

Route::post('/tokens/create', function (Request $request) {
    $token = $request->user()->createToken($request->token_name);

    return ['token' => $token->plainTextToken];
});

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

require __DIR__ . '/auth.php';

app/Http/Controllers/AuthorController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreAuthorRequest;
use App\Http\Requests\UpdateAuthorRequest;
use App\Models\Authors;
use Illuminate\Http\Request;

class AuthorController extends Controller
{
    public function index()
    {
        $authors = Authors::withCount('books')->get();
        return view('authorViews.authors', compact('authors'));
    }

    public function show(Authors $author)
    {   
        return view('authorViews.author', compact('author'));
    }

    public function store(StoreAuthorRequest $request)
    {
        $validated = $request->validated();

        $author = new Authors;
        $author->name = $request->name;
        $author->save();
        $newAuthorId = Authors::firstWhere('name', $request->name)->id;

        return redirect()->route('authors.show', ['author' => $newAuthorId]);
    }

    public function create()
    {
        return view(
            'authorViews.author-crud',
            [
                'type' => 'create'
            ]
        );
    }

    public function update(Authors $author)
    {
        return view(
            'authorViews.author-crud',
            [
                'type' => 'update',
                'author' => $author
            ]
        );
    }

    public function delete(Authors $author)
    {
        return view(
            'authorViews.author-crud',
            [
                'type' => 'delete',
                'author' => $author,
            ]
        );
    }

    public function destroy(Authors $author)
    {
        $authorDel = Authors::find($author->id);
        $authorDel->delete();

        return redirect()->route('authors.index');
    }

    public function save(UpdateAuthorRequest $request)
    {
        $validated = $request->validated();

        $authorId = $request->route('author');
        $author = Authors::find($authorId);
        $author->name = $request->name;
        $author->save();

        return redirect()->route('authors.show', ['author' => $authorId]);
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

resources/views/authorViews/author-crud.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            @if($type === 'create') Создание автора @endif
            @if($type === 'update') Изменение автора @endif
            @if($type === 'delete') Удаление автора @endif
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 text-gray-900">
                    @auth
                    @if ($type === 'update')
                    <x-author.form action="{{route('authors.save', ['author' => $author->id])}}" method='put' :type=$type :author='$author' />
                    @endif
                    @if ($type === 'delete')
                    <x-author.alert-delete :author='$author'/>
                    @endif
                    @if ($type === 'create')
                    <x-author.form action="{{route('authors.store')}}" method='post' :type=$type />
                    @endif
                    @else
                    Инфа не для авторизованных
                    @endauth
                </div>
            </div>
        </div>
    </div>

</x-app-layout>

resources/views/authorViews/author.blade.php
<x-app-layout>
    <x-slot name="header">
        <div class="w-full flex justify-between">
            <div>
                <h2 class="font-normal text-base text-gray-800 leading-tight">
                    Автор
                </h2>
                <h2 class="font-semibold text-xl text-gray-800 leading-tight">
                    {{ $author->name }}
                </h2>
            </div>
            <div>
                <a href="{{route('authors.index')}}">
                    <x-secondary-button type='button'>{{ __('<- Назад') }}</x-secondary-button>
                </a>
            </div>
        </div>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="flex justify-between p-6 text-gray-900">
                    @auth
                    <div>
                        <a href="{{route('authors.update', ['author' => $author->id])}}">
                            <x-secondary-button type='button'>{{ __('Изменить') }}</x-secondary-button>
                        </a>
                        <a href="{{route('authors.delete', ['author' => $author->id])}}">
                            <x-danger-button type='button'>{{ __('Удалить') }}</x-danger-button>
                        </a>
                    </div>
                    @else
                    Информация не для авторизованных
                    @endauth
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/authorViews/authors.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Авторы') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 text-gray-900 flex justify-between">
                    @auth
                    <div>
                        @foreach($authors as $author)
                        <div> <a href="{{route('authors.show', ['author' => $author->id])}}">{{$author->name}} ({{$author->books_count}})</a></div>
                        @endforeach
                    </div>
                    <a href="{{route('author.create')}}">
                        <x-primary-button type='button'>{{ __('Добавить автора') }}</x-primary-button>
                    </a>
                    @else
                    Инфа не для авторизованных
                    @endauth
                </div>
            </div>
        </div>
    </div>
</x-app-layout>